# Generated by Django 6.0 on 2025-12-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDEUM'), ('L', 'LOW')], default='L', max_length=1)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
